DROP TABLE IF EXISTS users

CREATE TABLE users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_name VARCHAR(20) NOT NULL,
  password_hash VARCHAR NOT NULL,
  user_role VARCHAR(10) NOT NULL
);
